- name: Install repo tools
  apt:
    state: latest
    package:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7EA0A9C3F273FCD8

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution.lower() }} {{ ansible_lsb.codename }} stable"

- name: Update apt
  become: yes
  apt:
    cache_valid_time: 1800
    update_cache: yes

- name: Install docker
  apt:
    state: latest
    allow_unauthenticated: yes
    update_cache: yes
    package:
      - docker-ce

- name: Check that the somefile.conf exists
  stat:
    path: "/usr/local/bin/docker-compose"
  register: docker_compose_result

- name: Install docker-compose
  uri:
    state: present
    dest: "/usr/local/bin/docker-compose"
    url: "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-{{ ansible_system.lower() }}-{{ ansible_machine }}"
  when: docker_compose_result.stat.exists == False

- name: Add the user to the group
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker

- name: Modify permimssions
  file:
    mode: "+x"
    path: "/usr/local/bin/docker-compose"
