- name: Install repo tools
  apt:
    state: latest
    package:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution.lower() }} {{ ansible_lsb.codename }} stable"

- name: Add repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7EA0A9C3F273FCD8

- name: Update apt
  become: yes
  apt:
    cache_valid_time: 1800
    update_cache: yes

- name: Install docker
  apt:
    state: latest
    allow_unauthenticated: yes
    package:
      - docker-ce
